name: codespell-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  codespell-check:
    runs-on: codespell-check

    steps:
    - uses: actions/checkout@v3

    - name: Run codespell
      run: codespell
