name: codespell-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  codespell-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install codespell tool
      run: sudo apt-get install codespell

    - name: Run codespell
      run: codespell
