name: run-unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update platform
      run: sudo apt-get update

    - name: Install Boost libraries
      run: sudo apt-get install libboost-all-dev

    - name: Install Nlohmann JSON library
      run: sudo apt-get install nlohmann-json3-dev

    - name: Install cURL libraries
      run: sudo apt-get install curl libssl-dev libcurl4-openssl-dev

    - name: Install GoogleTest libraries
      run: sudo apt-get install libgmock-dev libgtest-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run unit tests
      run: ${{github.workspace}}/build/test/runUnitTests
